version: "3.9"
services:
  backend:
    image: ghcr.io/peterkappelt/prapp-backend:dev
    networks:
      - internal
    volumes:
      - ./settings.py:/app/prapp/settings.py
    ports: 
      - 8000:8000
    logging:
      driver: journald
  web: 
    image: ghcr.io/peterkappelt/prapp-web:dev
    networks:
      - internal
      - public
    ports:
      - 8000:8000
    logging:
      driver: journald
networks:
  internal:
  public:
